### ISSUE TITLE
Not working with Black Studio TinyMCE Widget 2.2.6

### ISSUE THREAD

**Issue by boracon** [WPGlobus/wpglobus-for-black-studio-tinymce-widget#1]
It seems a great widget but It's not working with Black Studio TinyMCE Widget 2.2.6. I've loaded Black Studio a couple of days ago. The version 2.2.6 was in WP site.
Widget extension's language tabs don't listed among visual editor menu's.

**Comment by alexgff** [comment]
@boracon I checked with standard themes 2014 and 2015 also with theme Ample. WPGlobus add-on 1.0.1 works fine with Black Studio TinyMCE Widget plugin 2.2.6

**Comment by tivnet** [comment]
@boracon So, if it does not work on your site, the reason could be somewhere in your theme or other plugins. Can you please check if switching to a standard theme fixes the issue, and if not then try switching off other plugins.
Please let us know.
Thank you!

**Comment by boracon** [comment]
Hi Gregory/Alex

Switching to a standard theme didn't fix it. Then I switched off all the
plugins and switched on by various orders. But nothing changed. Is it
possible that you check for me?




2015-09-03 4:59 GMT+03:00 Alex Gor <notifications@github.com>:

**Comment by alexgff** [comment]
@boracon 
I can take a look to the site. You can send temp admin access via form http://www.wpglobus.com/pg/contact-us/

**Comment by alexgff** [comment]
@boracon 
Is this issue completed?

**Comment by tivnet** [comment]
@boracon Hi Borahan, I am going to close this issue, because as we discovered, the problem was in the PageBuilder and not the BS TinyMCE.

**Comment by boracon** [comment]
You're great team.

I was thinking that if I enter also Turkish and English text into same
page. Then do I have to wait for your solution?

2015-09-03 19:02 GMT+03:00 Gregory Karpinsky <notifications@github.com>:

**Comment by tivnet** [comment]
You can try. It could be a solution until we find the way to work with PageBuilder
