### ISSUE TITLE
Issues on Customizer

### ISSUE THREAD

**Issue by marcochiesi** [WPGlobus/wpglobus-for-black-studio-tinymce-widget#2]
Hi there,
I am the author of Black Studio TinyMCE Widget, and I am glad that you are providing a compatibility plugin for WPGlobus.
I noticed a problem when running the plugin on Theme Customizer: the widget titles and texts are not rendered correctly and they have the WPGlobus markup visible (i.e. {:en}).
I did not debug the issue, but please let me know if any modification is needed on the Black Studio side (you may also send a pull request).
Cheers.

**Comment by tivnet** [comment]
Hello Marco, very glad to meet you!

I will assign this ticket to my partnet Alex @alexgff who wrote most of the code related to Black Studio and customizer. He will be able to take it from here.

Appreciate your call, and hope we'll manage to get the 100% compatibility together.

**Comment by alexgff** [comment]
@marcochiesi 
I know about issue with customizer and I have plan to make add-on compatible with it.
Thank you for suggestion I hope it will helps

**Comment by alexgff** [comment]
@marcochiesi you can check plugin on Theme Customizer. It works.
